name: release-main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  RELEASE_PACKAGES: ".artifacts/package/release/*.nupkg"
  RELEASE_DISTRO: ".artifacts/elastic-distribution/*"

jobs:
  release:
    runs-on:
      group: elastic-otel-dotnet
      labels: elastic-otel-dotnet-ubuntu24-16
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/workflows/bootstrap
        with:
          skip-cache: 'true'

      # Run the release script to generate the distribution and packages
      # The redistributable artifacts are needed for the test step, and the packages are needed for the publish steps that follow
      - name: Release
        run: ./build.sh release

      - name: Test
        run: ./build.sh test --skip-build --skip-restore
        
      - name: Generate build provenance (Distribution)
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4
        with:
          subject-path: "${{ github.workspace }}/${{ env.RELEASE_DISTRO }}"
          
      - name: Generate build provenance (Packages)
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4
        with:
          subject-path: "${{ github.workspace }}/${{ env.RELEASE_PACKAGES }}"

      # Push to feedz.io 
      - name: publish canary packages to feedz.io
        run: dotnet nuget push '${{ env.RELEASE_PACKAGES }}' -k ${{ secrets.FEEDZ_IO_API_KEY }} -s ${{ secrets.FEEDZ_IO_API_URL }} --skip-duplicate --no-symbols
          
      # Push to GHPR for advertising purposes on the github landing page.
      # Sadly this still requires authentication to use as a nuget package repository
      - name: Publish canary packages github package repository
        shell: bash
        # this is a best effort to push to GHPR, we've observed it being unavailable intermittently
        continue-on-error: true
        run: dotnet nuget push '${{ env.RELEASE_PACKAGES }}' -k ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/elastic/index.json" --skip-duplicate --no-symbols 